import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import {
  contacts,
  inventoryProperties,
  units,
} from "./core-domain-schema";
import { agencies, profiles } from "./schema";

export const financeSequences = sqliteTable(
  "finance_sequences",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    sequenceKey: text("sequence_key").notNull(),
    documentType: text("document_type").notNull(),
    year: integer("year").notNull(),
    prefix: text("prefix").notNull(),
    padding: integer("padding").notNull().default(6),
    nextNumber: integer("next_number").notNull().default(1),
    updatedAt: integer("updated_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [uniqueIndex("finance_sequences_unique").on(table.agencyId, table.sequenceKey)],
);

export const paymentSchedules = sqliteTable(
  "payment_schedules",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    scheduleNumber: text("schedule_number").notNull(),
    sourceType: text("source_type").notNull(),
    sourceId: text("source_id"),
    payerContactId: text("payer_contact_id").notNull().references(() => contacts.id, { onDelete: "restrict" }),
    propertyId: text("property_id").references(() => inventoryProperties.id, { onDelete: "restrict" }),
    unitId: text("unit_id").references(() => units.id, { onDelete: "restrict" }),
    status: text("status").notNull().default("draft"),
    totalAmount: real("total_amount").notNull(),
    paidAmount: real("paid_amount").notNull().default(0),
    currency: text("currency").notNull().default("USD"),
    description: text("description"),
    activatedAt: integer("activated_at"),
    completedAt: integer("completed_at"),
    cancelledAt: integer("cancelled_at"),
    createdBy: text("created_by").references(() => profiles.id, { onDelete: "set null" }),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
    updatedAt: integer("updated_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [
    uniqueIndex("payment_schedules_agency_number_unique").on(table.agencyId, table.scheduleNumber),
    index("payment_schedules_source_idx").on(table.agencyId, table.sourceType, table.sourceId),
    index("payment_schedules_status_idx").on(table.agencyId, table.status, table.updatedAt),
    index("payment_schedules_payer_idx").on(table.agencyId, table.payerContactId, table.status),
  ],
);

export const paymentScheduleItems = sqliteTable(
  "payment_schedule_items",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    scheduleId: text("schedule_id").notNull().references(() => paymentSchedules.id, { onDelete: "cascade" }),
    sequence: integer("sequence").notNull(),
    label: text("label").notNull(),
    labelAr: text("label_ar"),
    dueAt: integer("due_at").notNull(),
    amount: real("amount").notNull(),
    paidAmount: real("paid_amount").notNull().default(0),
    status: text("status").notNull().default("pending"),
    notes: text("notes"),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
    updatedAt: integer("updated_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [
    uniqueIndex("payment_schedule_items_sequence_unique").on(table.agencyId, table.scheduleId, table.sequence),
    index("payment_schedule_items_due_idx").on(table.agencyId, table.status, table.dueAt),
  ],
);

export const invoices = sqliteTable(
  "invoices",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    invoiceNumber: text("invoice_number").notNull(),
    contactId: text("contact_id").notNull().references(() => contacts.id, { onDelete: "restrict" }),
    sourceType: text("source_type").notNull().default("manual"),
    sourceId: text("source_id"),
    scheduleId: text("schedule_id").references(() => paymentSchedules.id, { onDelete: "set null" }),
    scheduleItemId: text("schedule_item_id").references(() => paymentScheduleItems.id, { onDelete: "set null" }),
    propertyId: text("property_id").references(() => inventoryProperties.id, { onDelete: "restrict" }),
    unitId: text("unit_id").references(() => units.id, { onDelete: "restrict" }),
    status: text("status").notNull().default("draft"),
    issueDate: integer("issue_date").notNull(),
    dueAt: integer("due_at").notNull(),
    subtotal: real("subtotal").notNull(),
    taxAmount: real("tax_amount").notNull().default(0),
    discountAmount: real("discount_amount").notNull().default(0),
    totalAmount: real("total_amount").notNull(),
    paidAmount: real("paid_amount").notNull().default(0),
    balanceDue: real("balance_due").notNull(),
    currency: text("currency").notNull().default("USD"),
    notes: text("notes"),
    issuedAt: integer("issued_at"),
    paidAt: integer("paid_at"),
    voidedAt: integer("voided_at"),
    voidReason: text("void_reason"),
    createdBy: text("created_by").references(() => profiles.id, { onDelete: "set null" }),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
    updatedAt: integer("updated_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [
    uniqueIndex("invoices_agency_number_unique").on(table.agencyId, table.invoiceNumber),
    index("invoices_contact_status_idx").on(table.agencyId, table.contactId, table.status),
    index("invoices_due_idx").on(table.agencyId, table.status, table.dueAt),
    index("invoices_source_idx").on(table.agencyId, table.sourceType, table.sourceId),
  ],
);

export const invoiceLines = sqliteTable(
  "invoice_lines",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    invoiceId: text("invoice_id").notNull().references(() => invoices.id, { onDelete: "cascade" }),
    sequence: integer("sequence").notNull(),
    description: text("description").notNull(),
    descriptionAr: text("description_ar"),
    quantity: real("quantity").notNull().default(1),
    unitPrice: real("unit_price").notNull(),
    taxRate: real("tax_rate").notNull().default(0),
    lineSubtotal: real("line_subtotal").notNull(),
    lineTax: real("line_tax").notNull().default(0),
    lineTotal: real("line_total").notNull(),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [
    uniqueIndex("invoice_lines_sequence_unique").on(table.agencyId, table.invoiceId, table.sequence),
    index("invoice_lines_invoice_idx").on(table.agencyId, table.invoiceId),
  ],
);

export const receipts = sqliteTable(
  "receipts",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    receiptNumber: text("receipt_number").notNull(),
    contactId: text("contact_id").notNull().references(() => contacts.id, { onDelete: "restrict" }),
    status: text("status").notNull().default("posted"),
    paymentDate: integer("payment_date").notNull(),
    amount: real("amount").notNull(),
    allocatedAmount: real("allocated_amount").notNull().default(0),
    currency: text("currency").notNull().default("USD"),
    paymentMethod: text("payment_method").notNull(),
    externalReference: text("external_reference"),
    chequeNumber: text("cheque_number"),
    bankName: text("bank_name"),
    notes: text("notes"),
    receivedBy: text("received_by").references(() => profiles.id, { onDelete: "set null" }),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
    voidedAt: integer("voided_at"),
    voidedBy: text("voided_by").references(() => profiles.id, { onDelete: "set null" }),
    voidReason: text("void_reason"),
  },
  (table) => [
    uniqueIndex("receipts_agency_number_unique").on(table.agencyId, table.receiptNumber),
    index("receipts_contact_date_idx").on(table.agencyId, table.contactId, table.paymentDate),
    index("receipts_status_date_idx").on(table.agencyId, table.status, table.paymentDate),
  ],
);

export const receiptAllocations = sqliteTable(
  "receipt_allocations",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    receiptId: text("receipt_id").notNull().references(() => receipts.id, { onDelete: "restrict" }),
    invoiceId: text("invoice_id").notNull().references(() => invoices.id, { onDelete: "restrict" }),
    amount: real("amount").notNull(),
    status: text("status").notNull().default("active"),
    allocatedBy: text("allocated_by").references(() => profiles.id, { onDelete: "set null" }),
    allocatedAt: integer("allocated_at").notNull().$defaultFn(() => Date.now()),
    reversedAt: integer("reversed_at"),
    reversedBy: text("reversed_by").references(() => profiles.id, { onDelete: "set null" }),
    reversalReason: text("reversal_reason"),
  },
  (table) => [
    index("receipt_allocations_receipt_idx").on(table.agencyId, table.receiptId, table.status),
    index("receipt_allocations_invoice_idx").on(table.agencyId, table.invoiceId, table.status),
  ],
);

export const expenses = sqliteTable(
  "expenses",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    expenseNumber: text("expense_number").notNull(),
    category: text("category").notNull(),
    vendorContactId: text("vendor_contact_id").references(() => contacts.id, { onDelete: "restrict" }),
    propertyId: text("property_id").references(() => inventoryProperties.id, { onDelete: "restrict" }),
    unitId: text("unit_id").references(() => units.id, { onDelete: "restrict" }),
    sourceType: text("source_type").notNull().default("manual"),
    sourceId: text("source_id"),
    status: text("status").notNull().default("draft"),
    description: text("description").notNull(),
    incurredAt: integer("incurred_at").notNull(),
    dueAt: integer("due_at"),
    subtotal: real("subtotal").notNull(),
    taxAmount: real("tax_amount").notNull().default(0),
    totalAmount: real("total_amount").notNull(),
    currency: text("currency").notNull().default("USD"),
    paymentMethod: text("payment_method"),
    paymentReference: text("payment_reference"),
    notes: text("notes"),
    submittedAt: integer("submitted_at"),
    approvedAt: integer("approved_at"),
    approvedBy: text("approved_by").references(() => profiles.id, { onDelete: "set null" }),
    paidAt: integer("paid_at"),
    paidBy: text("paid_by").references(() => profiles.id, { onDelete: "set null" }),
    rejectionReason: text("rejection_reason"),
    createdBy: text("created_by").references(() => profiles.id, { onDelete: "set null" }),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
    updatedAt: integer("updated_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [
    uniqueIndex("expenses_agency_number_unique").on(table.agencyId, table.expenseNumber),
    index("expenses_status_date_idx").on(table.agencyId, table.status, table.incurredAt),
    index("expenses_property_idx").on(table.agencyId, table.propertyId, table.status),
    index("expenses_vendor_idx").on(table.agencyId, table.vendorContactId, table.status),
  ],
);

export const commissions = sqliteTable(
  "commissions",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    commissionNumber: text("commission_number").notNull(),
    transactionType: text("transaction_type").notNull(),
    transactionId: text("transaction_id").notNull(),
    status: text("status").notNull().default("draft"),
    basisType: text("basis_type").notNull(),
    basisValue: real("basis_value").notNull(),
    transactionValue: real("transaction_value").notNull(),
    grossCommission: real("gross_commission").notNull(),
    approvedAmount: real("approved_amount"),
    paidAmount: real("paid_amount").notNull().default(0),
    currency: text("currency").notNull().default("USD"),
    notes: text("notes"),
    submittedAt: integer("submitted_at"),
    approvedAt: integer("approved_at"),
    approvedBy: text("approved_by").references(() => profiles.id, { onDelete: "set null" }),
    createdBy: text("created_by").references(() => profiles.id, { onDelete: "set null" }),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
    updatedAt: integer("updated_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [
    uniqueIndex("commissions_agency_number_unique").on(table.agencyId, table.commissionNumber),
    uniqueIndex("commissions_transaction_unique").on(table.agencyId, table.transactionType, table.transactionId),
    index("commissions_status_idx").on(table.agencyId, table.status, table.updatedAt),
  ],
);

export const commissionSplits = sqliteTable(
  "commission_splits",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    commissionId: text("commission_id").notNull().references(() => commissions.id, { onDelete: "cascade" }),
    recipientType: text("recipient_type").notNull(),
    recipientProfileId: text("recipient_profile_id").references(() => profiles.id, { onDelete: "restrict" }),
    recipientContactId: text("recipient_contact_id").references(() => contacts.id, { onDelete: "restrict" }),
    splitType: text("split_type").notNull(),
    splitValue: real("split_value").notNull(),
    amount: real("amount").notNull(),
    paidAmount: real("paid_amount").notNull().default(0),
    status: text("status").notNull().default("pending"),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
    updatedAt: integer("updated_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [
    index("commission_splits_commission_idx").on(table.agencyId, table.commissionId, table.status),
    index("commission_splits_profile_idx").on(table.agencyId, table.recipientProfileId, table.status),
    index("commission_splits_contact_idx").on(table.agencyId, table.recipientContactId, table.status),
  ],
);

export const commissionPayouts = sqliteTable(
  "commission_payouts",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    commissionId: text("commission_id").notNull().references(() => commissions.id, { onDelete: "restrict" }),
    splitId: text("split_id").notNull().references(() => commissionSplits.id, { onDelete: "restrict" }),
    amount: real("amount").notNull(),
    currency: text("currency").notNull(),
    paymentDate: integer("payment_date").notNull(),
    paymentMethod: text("payment_method").notNull(),
    paymentReference: text("payment_reference"),
    status: text("status").notNull().default("posted"),
    paidBy: text("paid_by").references(() => profiles.id, { onDelete: "set null" }),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
    voidedAt: integer("voided_at"),
    voidReason: text("void_reason"),
  },
  (table) => [index("commission_payouts_split_idx").on(table.agencyId, table.splitId, table.status)],
);

export const financeEvents = sqliteTable(
  "finance_events",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    eventType: text("event_type").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    amount: real("amount"),
    currency: text("currency"),
    actorId: text("actor_id").references(() => profiles.id, { onDelete: "set null" }),
    metadata: text("metadata"),
    createdAt: integer("created_at").notNull().$defaultFn(() => Date.now()),
  },
  (table) => [
    index("finance_events_entity_idx").on(table.agencyId, table.entityType, table.entityId, table.createdAt),
    index("finance_events_type_date_idx").on(table.agencyId, table.eventType, table.createdAt),
  ],
);

export const financeReconciliationRuns = sqliteTable(
  "finance_reconciliation_runs",
  {
    id: text("id").primaryKey(),
    agencyId: text("agency_id").notNull().references(() => agencies.id, { onDelete: "cascade" }),
    status: text("status").notNull(),
    discrepancyCount: integer("discrepancy_count").notNull().default(0),
    result: text("result").notNull(),
    runBy: text("run_by").references(() => profiles.id, { onDelete: "set null" }),
    startedAt: integer("started_at").notNull(),
    completedAt: integer("completed_at").notNull(),
  },
  (table) => [index("finance_reconciliation_runs_idx").on(table.agencyId, table.completedAt)],
);
